---
# handlers file for lamp
 - name: restart apache2 
   service:
     name: apache2
     enabled: yes
     state: restarted
   when: ansible_os_family == "Debian"  
 - name: restart httpd
   service:
     name: httpd
     enabled: yes
     state: restarted
   when: ansible_os_family == "RedHat" 
